# Generated by Django 5.1.7 on 2025-04-14 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Verification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_image",
                    models.ImageField(blank=True, null=True, upload_to="user_uploads/"),
                ),
                ("verified", models.BooleanField(blank=True, null=True)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("verified", "Verified"),
                            ("not_verified", "Not Verified"),
                        ],
                        default="not_verified",
                        max_length=20,
                    ),
                ),
                ("distance", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "default_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.defaultimage",
                    ),
                ),
            ],
        ),
    ]
