# Generated by Django 5.1.7 on 2025-04-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_verification"),
    ]

    operations = [
        migrations.CreateModel(
            name="Identification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="identification/")),
                ("embedding", models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
