# Generated by Django 5.1.7 on 2025-04-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_facialexpression"),
    ]

    operations = [
        migrations.CreateModel(
            name="Otherestimations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="estimations/")),
                ("age", models.IntegerField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
